const EXAMPLE_ACTION = 'EXAMPLE_ACTION';
const EXAMPLE_ACTION_ERROR = 'EXAMPLE_ACTION_ERROR';
const EXAMPLE_ACTION_PENDING = 'EXAMPLE_ACTION_PENDING';
const EXAMPLE_ACTION_FULFILLED = 'EXAMPLE_ACTION_FULFILLED';

export {
  EXAMPLE_ACTION,
  EXAMPLE_ACTION_ERROR,
  EXAMPLE_ACTION_PENDING,
  EXAMPLE_ACTION_FULFILLED,
};
